version: '3'
services:
    coaster-api-dev:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
        ports:
            - 3050:3050
        volumes:
            - ./logs:/app/logs
            - ./database:/app/database
    coaster-api-prod:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
        ports:
            - 3051:3051
        volumes:
            - ./logs:/app/logs
            - ./database:/app/database
